name: Build and Upload

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Zip it good
      run: zip -9 -r Broker_CTA_`$GITHUB_RUN_ID`.zip $GITHUB_WORKSPACE/Broker_CTA/* LICENSE README.md
      
    - name: What is here
      run: ls -lsa
      
    - name: Parse WoW Addon Verions
      id: get_versions
      uses: icbat/parse-wow-addon-version@v0.0.1
      with:
        tocfile:  Broker_CTA/Broker_CTA.toc
    
    - name: Echo Verisons
      run: echo ${{ steps.get_versions.outputs.supported_version }} ${{ steps.get_versions.outputs.addon_version }}

    - name: Upload to WoW Interface
      uses: icbat/wow-addon-upload-action@v0.0.4
      with:
        id: 25623
        zipFilePath: Broker_CTA_`$GITHUB_RUN_ID`.zip
        compatible: 80000,80307,80300,80205
        version: ${{ steps.get_versions.outputs.addon_version }}
        apiKey: ${{ secrets.WOW_INTERFACE }}
